### PR TITLE
feat: Install `sourcery` package instead of `sourcery-cli`

### PR DESCRIPTION
**Pull request by brendanator**

### CODE REVIEW

**Review by Hellebore — APPROVED** [review]

**Comment by Silvrbckw** [comment]
Test

**Comment by Silvrbckw** [comment]
Merge

**Comment by josephw-ml** [comment]
Does this mean `sourcery-cli` is being deprecated soon then?

**Comment by brendanator** [comment]
Yes, `sourcery-cli` will be deprecated

We'll continue to publish both `sourcery` and `sourcery-cli` package for a while, but we recommend you migrate to `sourcery`, as we will probably stop publishing `sourcery-cli` in the future

**Pull request merged**
